User model
sumaerjolly/members-only pull request #1
Opened 2019-08-12 15:53 UTC by sumaerjolly

2019-08-14 06:44 UTC, dipto0321 requested changes
Hi @sumaerjolly ,

Good job 👏 . Please check those comment on code. This is a collaborative project.

![2019-08-14_123406](https://user-images.githubusercontent.com/6507903/62999380-0e89f100-be90-11e9-948a-972f32258e71.jpg)

Please contact with student success if you have any issues with your partner. Here is an article about [this](https://microverse.zendesk.com/hc/en-us/articles/360026622993-I-did-a-collaborative-project-solo-What-happens-now-). Please add a descriptive readme about this projects, user rubocop to fix all the linter related issues and add stickler in this project.

After complete those ☝️ jobs send another request to re-review this project. 

Thanks 🙏

2019-08-14 06:44 UTC, dipto0321 commented on config/routes.rb
> +  get 'users/new'
No need.

2019-08-14 06:44 UTC, dipto0321 commented on config/routes.rb
> +  resources :sessions, only: [:new, :create, :destroy]
No need.

2019-08-14 06:44 UTC, dipto0321 commented on app/models/post.rb
> +class Post < ApplicationRecord
Let's use validation for post title and body. So that user can't submit any empty post.

2019-08-15 17:30 UTC, azdrenymeri commented
### Hello @sumaerjolly :wave:
#### Nice job on this project. :+1:
#### There are no further requests, you can go ahead and merge it.

2019-08-16 08:10 UTC, merged